import { jsPDF } from "jspdf";
import type { TimetableSlot } from "../types";

const dayOrder: TimetableSlot["day"][] = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

export const downloadTimetablePdf = ({
  className,
  program,
  semester,
  slots,
  filename,
}: {
  className: string;
  program: string;
  semester: string;
  slots: TimetableSlot[];
  filename?: string;
}) => {
  const document = new jsPDF();
  const sortedSlots = [...slots].sort((left, right) => {
    const dayDifference = dayOrder.indexOf(left.day) - dayOrder.indexOf(right.day);
    return dayDifference || left.startTime.localeCompare(right.startTime);
  });

  document.setFillColor(30, 41, 59);
  document.rect(0, 0, 210, 34, "F");
  document.setTextColor(255, 255, 255);
  document.setFontSize(20);
  document.setFont("helvetica", "bold");
  document.text("UniNexus Academic Timetable", 14, 16);
  document.setFontSize(10);
  document.setFont("helvetica", "normal");
  document.text(`${program} | ${className} | ${semester}`, 14, 25);

  const columns = ["Day", "Time", "Course", "Lecturer", "Room"];
  const columnX = [14, 43, 79, 126, 171];
  let y = 47;

  document.setFillColor(16, 185, 129);
  document.rect(14, y - 7, 182, 9, "F");
  document.setTextColor(255, 255, 255);
  document.setFontSize(9);
  document.setFont("helvetica", "bold");
  columns.forEach((column, index) => document.text(column, columnX[index], y));
  y += 10;

  document.setFont("helvetica", "normal");
  document.setTextColor(30, 41, 59);
  document.setFontSize(8.5);

  if (sortedSlots.length === 0) {
    document.text("No timetable slots have been published for this class.", 14, y + 4);
  } else {
    sortedSlots.forEach((slot, index) => {
      if (y > 275) {
        document.addPage();
        y = 20;
      }

      if (index % 2 === 0) {
        document.setFillColor(241, 245, 249);
        document.rect(14, y - 7, 182, 12, "F");
      }

      document.setTextColor(30, 41, 59);
      document.text(slot.day, columnX[0], y);
      document.text(`${slot.startTime} - ${slot.endTime}`, columnX[1], y);
      document.text(document.splitTextToSize(`${slot.courseCode} - ${slot.courseTitle}`, 42)[0], columnX[2], y);
      document.text(document.splitTextToSize(slot.lecturerName, 40)[0], columnX[3], y);
      document.text(document.splitTextToSize(slot.classroom, 25)[0], columnX[4], y);
      y += 12;
    });
  }

  document.setDrawColor(203, 213, 225);
  document.line(14, 282, 196, 282);
  document.setFontSize(8);
  document.setTextColor(100, 116, 139);
  document.text(`Generated by UniNexus on ${new Date().toLocaleDateString()}`, 14, 290);
  document.text("Official timetable", 196, 290, { align: "right" });

  document.save(filename || `uninexus-${className.toLowerCase().replace(/\s+/g, "-")}-timetable.pdf`);
};
